name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run unit tests
        run: docker compose -f docker/docker-compose.unit.yaml run --rm tests /app/scripts/run_tests.sh unit

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tfvars file from secret
        run: |
          mkdir -p infra/env/local_dev/
          cat > infra/env/local_dev/terraform.tfvars<<'EOF'
          ${{ secrets.TF_VARS_CI }}
          EOF
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and cache integration image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.integration
          load: true
          tags: ci-test-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run integration tests
        run: |
#          docker compose -f docker/docker-compose.ci.yaml up -d
#          docker compose -f docker/docker-compose.ci.yaml run --rm tests /app/scripts/init_localstack.sh
#          docker compose -f docker/docker-compose.ci.yaml run --rm tests /app/scripts/run_tests.sh integration

      - name: Tear down services
        if: always()
        run: docker compose -f docker/docker-compose.ci.yaml down